services:
  _defaults:
    public: false
    autowire: true

  OxidAcademy\ProductDataReader\Service\DataReader:
    public: true

  OxidAcademy\ProductDataReader\Command\DataReaderCommand:
    tags:
      - { name: 'console.command' }
